### ISSUE TITLE
UPM support

### ISSUE THREAD

**Issue by jasursadikov** [mochi-neko/simple-reorderable-list-unity#3]
Could you add UPM [Unity Package Manager] support to this repository?

More info: https://github.com/ashblue/unity-package-manager-git-example

I see that one guy @R0XU already made pull request to your repository and forked your repository
But I tried to use his repository in my project, but unfortunately, package manager fails to load it.

That would be awesome, if you add support of *package manager*!

**Comment by R0XU** [comment]
At first, I have to apologize to everyone😔
The cause of this fails is .meta files.
すいません、metaファイルの削除と不足が原因みたいです😔

I fixed it.
@vmp1r3  Please retry use my repository😃
修正してプッシュしなおしたので、僕のリポジトリで試してみてください😃
